// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugkdmalrbrsaptescadd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVna2RtYWxyYnJzYXB0ZXNjYWRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MzkzMjYsImV4cCI6MjA1NjExNTMyNn0.SQ7ouRdIdkXtr4e9NOd7CdXWIwdrsfDYjVb_kwTxOXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);