
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import './schema'; // Import the schema extension

const SUPABASE_URL = "https://xqjhoojjmyyajmwybgpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhxamhvb2pqbXl5YWptd3liZ3BkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNDYyNjIsImV4cCI6MjA1NzYyMjI2Mn0.4yMxSEqpI44XpDOCluQV-TfvbZnzXYXZj7f1rIFUdIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
